# Generated by Django 5.0.6 on 2024-07-12 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='patient',
            field=models.BooleanField(default=True),
        ),
    ]
