# Generated by Django 5.0.6 on 2024-07-12 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_patient_patient'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='staff',
            field=models.BooleanField(default=True),
        ),
    ]
